DubbelVy/Models/AuditElement.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Dubbelvy.Models
{
    public class AuditElement
    {
        [Display(Name = "Element ID")]
        public int Id { get; set; }

        [Required]
        [StringLength(30)]
        public string Topic { get; set; }

        [Required]
        public string Text { get; set; }

        [Required]
        public int Order { get; set; }

        [Display(Name = "Created on")]
        public DateTime CreateDateTime { get; set; }

        [Required]
        [Display(Name = "Created by")]
        public string CreatedById { get; set; }
        [Display(Name = "Created by")]
        public ApplicationUser CreatedBy { get; set; }

        public DateTime ModifiedDateTime { get; set; }

        [Required]
        public string ModifiedById { get; set; }
        public ApplicationUser ModifiedBy { get; set; }

        [Display(Name = "Audit Section")]
        public int SectionId { get; set; }
        public AuditSection Section { get; set; }

        [Display(Name = "Audit Choices")]
        public ICollection<AuditElementChoice> Choices { get; set; }

        public double? GetTotalPossiblePoints(ApplicationDbContext _context)
        {
            Choices = _context.AuditElementChoices.Where(c => c.ElementId == Id).ToList();

            if(Choices.Count > 0)
            {
                return Choices.Max(c => c.Score);
            }

            return null;
        }

        public void UpdateFromViewModel (AuditElementViewModel viewModel)
        {
            Topic = viewModel.Topic;
            Text = viewModel.Text;
            Order = viewModel.Order;
            ModifiedById = viewModel.ModifiedById;
            ModifiedDateTime = viewModel.ModifiedDateTime != null ? viewModel.ModifiedDateTime.Value : DateTime.Now;
        }
    }
}

DubbelVy/Models/AuditElementViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Dubbelvy.Models
{
    public class AuditElementViewModel
    {
        public int? Id { get; set; }

        [Required]
        [StringLength(30)]
        public string Topic { get; set; }

        [Required]
        public string Text { get; set; }

        [Required]
        [Display(Name = "Display Order")]
        public int Order { get; set; }

        [Display(Name = "Created")]
        public DateTime? CreateDateTime { get; set; }

        [Display(Name = "Created by")]
        public string CreatedById { get; set; }
        public ApplicationUser CreatedBy { get; set; }

        [Display(Name = "Modified")]
        public DateTime? ModifiedDateTime { get; set; }

        [Display(Name = "Modified by")]
        public string ModifiedById { get; set; }
        public ApplicationUser ModifiedBy { get; set; }

        [Display(Name = "Audit Section")]
        public int SectionId { get; set; }
        public AuditSectionViewModel Section { get; set; }

        [Display(Name = "Audit Choices")]
        public List<AuditElementChoiceViewModel> Choices { get; set; }
    }
}

DubbelVy/Controllers/AuditElementsController.cs
using Dubbelvy.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dubbelvy.Controllers
{
    public class AuditElementsController : Controller
    {
        private ApplicationDbContext _context;

        public AuditElementsController()
        {
            _context = new ApplicationDbContext();
        }
        
        public ActionResult Add(int id)
        {
            var auditSectionId = id;

            var auditSection = _context.AuditSections.Single(a => a.Id == auditSectionId);
            var auditTemaplate = _context.AuditTemplates.Single(a => a.Id == auditSection.AuditTemplateId);

            if(auditTemaplate.GetCompletedAuditCount(_context) == 0)
            {
                var viewModel = new AuditElementViewModel
                {
                    SectionId = id,
                    Section = new AuditSectionViewModel
                    {
                        AuditTemplate = new AuditTemplateViewModel()
                    }
                };

                AutoMapper.Mapper.Map(auditSection, viewModel.Section);
                AutoMapper.Mapper.Map(auditTemaplate, viewModel.Section.AuditTemplate);

                return View("Form", viewModel);
            }

            ViewBag.Message = "Unable to add element. Audits have already been completed using this audit template.";
            return RedirectToAction("Details", "AuditTemplates", new { id = auditTemaplate.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(AuditElementViewModel model)
        {
            var userId = User.Identity.GetUserId();
            var submitDateTime = DateTime.Now;
            model.CreateDateTime = submitDateTime;
            model.ModifiedDateTime = submitDateTime;
            model.CreatedById = userId;
            model.ModifiedById = userId;

            var auditSection = _context.AuditSections.Single(a => a.Id == model.SectionId);
            var auditTemaplate = _context.AuditTemplates.Single(a => a.Id == auditSection.AuditTemplateId);

            if (ModelState.IsValid)
            {
                var auditElement = new AuditElement();

                AutoMapper.Mapper.Map(model, auditElement);

                auditSection.ModifiedById = userId;
                auditSection.ModifiedDateTime = submitDateTime;
                auditTemaplate.ModifiedById = userId;
                auditTemaplate.ModifiedDateTime = submitDateTime;

                _context.AuditElements.Add(auditElement);
                _context.SaveChanges();

                var auditTemplateId = _context.AuditSections.Single(a => a.Id == auditElement.SectionId).AuditTemplateId;

                return RedirectToAction("Details", "AuditTemplates", new { id = auditTemplateId });
            }

            

            model.Section = new AuditSectionViewModel { AuditTemplate = new AuditTemplateViewModel() };

            AutoMapper.Mapper.Map(auditSection, model.Section);
            AutoMapper.Mapper.Map(auditTemaplate, model.Section.AuditTemplate);

            return View("Form", model);
        }

        public ActionResult Delete (int id)
        {
            var userId = User.Identity.GetUserId();
            var submitDateTime = DateTime.Now;

            var auditElement = _context.AuditElements.Single(a => a.Id == id);
            var auditSection = _context.AuditSections.Single(a => a.Id == auditElement.SectionId);
            var auditTemplate = _context.AuditTemplates.Single(a => a.Id == auditSection.AuditTemplateId);

            if(auditTemplate.GetCompletedAuditCount(_context) == 0)
            {
                var auditElementChoices = _context.AuditElementChoices.Where(a => a.ElementId == id).ToList();

                if (auditElementChoices.Count > 0)
                    _context.AuditElementChoices.RemoveRange(auditElementChoices);

                _context.AuditElements.Remove(auditElement);
                auditSection.ModifiedById = userId;
                auditSection.ModifiedDateTime = submitDateTime;
                auditTemplate.ModifiedById = userId;
                auditTemplate.ModifiedDateTime = submitDateTime;
                _context.SaveChanges();

                ViewBag.Message = "Audit element has been successfully deleted.";
            }
            else
            {
                ViewBag.Message = "Unable to delete audit element.  Audits have been completed using the audit template that the audit element belongs to.";
            }

            return RedirectToAction("Details", "AuditTemplates", new { id = auditTemplate.Id });
        }

        public ActionResult Details(int id)
        {
            var auditElement = _context.AuditElements
                .Include(a => a.Section.AuditTemplate)
                .Include(a => a.CreatedBy)
                .Include(a => a.ModifiedBy)
                .Single(a => a.Id == id);

            var viewModel = new AuditElementViewModel
            {
                Section = new AuditSectionViewModel { AuditTemplate = new AuditTemplateViewModel() }
            };

            AutoMapper.Mapper.Map(auditElement, viewModel);

            return View(viewModel);
        }

        public ActionResult Edit(int id)
        {
            var auditElement = _context.AuditElements
                .Include(a => a.Section.AuditTemplate)
                .Single(a => a.Id == id);

            if(auditElement.Section.AuditTemplate.GetCompletedAuditCount(_context) == 0)
            {
                var viewModel = new AuditElementViewModel
                {
                    Section = new AuditSectionViewModel { AuditTemplate = new AuditTemplateViewModel() }
                };

                AutoMapper.Mapper.Map(auditElement, viewModel);

                return View("Form", viewModel);
            }

            ViewBag.Message = "Unable to edit element.  Audits have already been completed using the audit template that it belongs to.";
            return RedirectToAction("Details", "AuditTemplates", new { id = auditElement.Section.AuditTemplateId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AuditElementViewModel model)
        {
            var userId = User.Identity.GetUserId();
            var submitDateTime = DateTime.Now;

            var auditElement = _context.AuditElements.Single(a => a.Id == model.Id);
            var auditSection = _context.AuditSections.Single(a => a.Id == auditElement.SectionId);
            var auditTemplate = _context.AuditTemplates.Single(a => a.Id == auditSection.AuditTemplateId);

            model.CreateDateTime = auditElement.CreateDateTime;
            model.CreatedById = auditElement.CreatedById;
            model.ModifiedDateTime = submitDateTime;
            model.ModifiedById = userId;

            if (ModelState.IsValid)
            {
                auditElement.UpdateFromViewModel(model);
                auditSection.ModifiedById = userId;
                auditSection.ModifiedDateTime = submitDateTime;
                auditTemplate.ModifiedById = userId;
                auditTemplate.ModifiedDateTime = submitDateTime;
                _context.SaveChanges();

                return RedirectToAction("Details", "AuditTemplates", new { id = auditTemplate.Id });
            }

            model.Section = new AuditSectionViewModel { AuditTemplate = new AuditTemplateViewModel() };
            AutoMapper.Mapper.Map(auditSection, model.Section);
            AutoMapper.Mapper.Map(auditTemplate, model.Section.AuditTemplate);
            return View("Form", model);
        }
    }
}

DubbelVy/Views/AuditElements/Details.cshtml
@model AuditElementViewModel
@{
    ViewBag.Title = "Audit Element Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>
<hr />
<div class="row">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(m => m.Topic)</dt>
            <dd>@Model.Topic</dd>
            <dt>@Html.DisplayNameFor(m => m.Text)</dt>
            <dd>@Model.Text</dd>
            <dt>@Html.DisplayNameFor(m => m.Order)</dt>
            <dd>@Model.Order</dd>
            <dt>@Html.DisplayNameFor(m => m.Section.AuditTemplateId)</dt>
            <dd>
                @Html.ActionLink($"{Model.Section.AuditTemplate.Title} V{Model.Section.AuditTemplate.Version}", "Details", "AuditTemplates", new { id = Model.Section.AuditTemplateId }, null)
            </dd>
            <dt>@Html.DisplayNameFor(m => m.SectionId)</dt>
            <dd>@Html.ActionLink(Model.Section.Description, "Details", "AuditSections", new { id = Model.SectionId }, null)</dd>
            <dt>@Html.DisplayNameFor(m => m.Section.Weight)</dt>
            <dd>@Model.Section.WeightDisplay</dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(m => m.CreateDateTime)</dt>
            <dd>@Model.CreateDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.CreatedById)</dt>
            <dd>@Model.CreatedBy.NameFLUser</dd>
            <dt>@Html.DisplayNameFor(m => m.ModifiedDateTime)</dt>
            <dd>@Model.ModifiedDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.ModifiedById)</dt>
            <dd>@Model.ModifiedBy.NameFLUser</dd>
        </dl>
    </div>
</div>

DubbelVy/Views/AuditElements/Form.cshtml
@model AuditElementViewModel
@{
    /**/

    ViewBag.Title = Model.Id != null ? "Edit Audit Element" : "New Audit Element";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>
<p style="font-style: italic">For @Model.Section.AuditTemplate.Title V@(Model.Section.AuditTemplate.Version) - @Model.Section.Description</p>
<hr />
@using (Html.BeginForm(Model.Id != null ? "Edit" : "Add", "AuditElements", FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Topic, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Topic, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Text, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Text, new { @class = "form-control", @rows = "5" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Order, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Order, new { @class = "form-control" })
        </div>
    </div>
    <div class="hidden">
        @Html.HiddenFor(m => m.SectionId)
        @Html.HiddenFor(m => m.Id)
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value=@(Model.Id != null ? "Save" : "Create") />
        </div>
    </div>
}
