DubbelVy/Models/Dispute.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Dubbelvy.Models
{
    public class Dispute
    {
        [Key]
        [ForeignKey("Audit")]
        public Guid AuditId { get; set; }
        public Audit Audit { get; set; }

        public string Comments { get; set; }

        public DateTime CreateDateTime { get; set; }

        public DateTime? SupervisorApproveDateTime { get; set; }

        public DateTime? DecisionDateTime { get; set; }

        public int? DecisionId { get; set; }
        public DisputeDecision Decision { get; set; }

        public string DeciderId { get; set; }
        public ApplicationUser Decider { get; set; }
    }
}

DubbelVy/Models/DisputeViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Dubbelvy.Models
{
    public class DisputeViewModel
    {
        [Display(Name = "Audit ID")]
        public Guid AuditId { get; set; }
        public Audit Audit { get; set; }

        [Display(Name = "Comment")]
        public string NewComment { get; set; }

        public string Comments { get; set; }

        [Display(Name = "Created")]
        public DateTime CreateDateTime { get; set; }

        [Display(Name = "Supervisor Approved")]
        public DateTime? SupervisorApproveDateTime { get; set; }

        [Display(Name = "Decision Date")]
        public DateTime? DecisionDateTime { get; set; }

        [Display(Name = "Decision")]
        public int? DecisionId { get; set; }
        public DisputeDecision Decision { get; set; }

        [Display(Name = "Decided by")]
        public string DeciderId { get; set; }
        public ApplicationUser Decider { get; set; }

        public List<DisputeDecision> DecisionOptions { get; set; }
    }
}

DubbelVy/Controllers/DisputesController.cs
using Dubbelvy.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Dubbelvy.Controllers
{
    public class DisputesController : Controller
    {
        private ApplicationDbContext _context;

        public DisputesController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult Create(Guid id)
        {
            var dispute = new Dispute
            {
                AuditId = id,
                Audit = _context.Audits
                .Include(a => a.Auditee)
                .Include(a => a.AuditTemplate)
                .Include(a => a.Supervisor)
                .Single(a => a.Id == id)
            };

            return View(dispute);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Dispute model)
        {
            var submitDateTime = DateTime.Now;
            var userId = User.Identity.GetUserId();
            var user = _context.Users.Single(u => u.Id == userId);

            if (!string.IsNullOrWhiteSpace(model.Comments))
            {
                var dispute = new Dispute
                {
                    AuditId = model.AuditId,
                    Comments = $"{user.NameFLUser} {submitDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")}\r\n" + model.Comments,
                    CreateDateTime = submitDateTime
                };

                _context.Disputes.Add(dispute);
                _context.SaveChanges();

                NotifySupervisor(dispute.AuditId);

                return RedirectToAction("Details", "Audits", new { id = dispute.AuditId });
            }
            model.Audit = _context.Audits
                .Include(a => a.Auditee)
                .Include(a => a.AuditTemplate)
                .Include(a => a.Supervisor)
                .Single(a => a.Id == model.AuditId);

            return View(model);
        }

        public ActionResult Details(Guid id)
        {
            var dispute = _context.Disputes
                .Include(d => d.Audit.Auditee)
                .Include(d => d.Audit.AuditTemplate)
                .Include(d => d.Audit.Supervisor)
                .Include(d => d.Decision)
                .Include(d => d.Decider)
                .Single(d => d.AuditId == id);
            var viewModel = new DisputeViewModel();

            AutoMapper.Mapper.Map(dispute, viewModel);

            viewModel.DecisionOptions = _context.DisputeDecisions.ToList();

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(DisputeViewModel model)
        {
            var userId = User.Identity.GetUserId();
            var user = _context.Users.Single(u => u.Id == userId);
            var submitDateTime = DateTime.Now;
            var dispute = _context.Disputes.Single(d => d.AuditId == model.AuditId);

            if(dispute.DecisionId != model.DecisionId)
            {
                dispute.DecisionId = model.DecisionId;
                if(dispute.DecisionId != null)
                {
                    var decision = _context.DisputeDecisions.Single(d => d.Id == dispute.DecisionId);
                    dispute.DecisionDateTime = submitDateTime;
                    dispute.DeciderId = userId;
                    dispute.Comments = $"{user.NameFLUser} {submitDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")}\r\n" +
                        "Updated decision to " + decision.Text + "\r\n\r\n" + dispute.Comments;
                }
                else
                {
                    dispute.DecisionDateTime = null;
                    dispute.DeciderId = userId;
                    dispute.Comments = $"{user.NameFLUser} {submitDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")}\r\n" +
                        "Removed decision.  Dispute now pending deicision" + "\r\n\r\n" + dispute.Comments;
                }
            }
            if (!string.IsNullOrWhiteSpace(model.NewComment))
            {
                dispute.Comments = $"{user.NameFLUser} {submitDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")}\r\n" +
                    model.NewComment + "\r\n\r\n" + dispute.Comments;
            }

            _context.SaveChanges();

            return RedirectToAction("Details", new { id = dispute.AuditId });
        }

        public ActionResult Index()
        {
            var disputes = _context.Disputes
                .Include(d => d.Audit.Auditee)
                .Include(d => d.Audit.Auditor)
                .Include(d => d.Audit.AuditTemplate)
                .Include(d => d.Audit.Supervisor)
                .Include(d => d.Decision)
                .ToList();

            return View(disputes);
        }

        public void NotifySupervisor (Guid AuditId)
        {
            var audit = _context.Audits
                .Include(a => a.Auditee)
                .Include(a => a.AuditTemplate)
                .Include(a => a.Dispute)
                .Include(a => a.Supervisor)
                .Single(a => a.Id == AuditId);

            var message = new MailMessage();
            message.To.Add(new MailAddress(audit.Supervisor.Email));
            message.Subject = $"Audit Dispute - {audit.Auditee.NameFLUser} - {audit.WorkDateTime.ToString("MM/dd/yyyy")} {audit.WorkIdentifier}";
            message.Body = string.Format(DubbelVyEmail.DisputeSupervisorMessage, audit.Auditee.NameFirstMLast, audit.WorkIdentifier,
                audit.WorkDateTime.ToString("MM/dd/yyyy"), audit.AuditDateTime.ToString("MM/dd/yyyy"), audit.Dispute.Comments,
                audit.Id, audit.AuditTemplate.TitleVersion);

            DubbelVyEmail.Send(message);
        }

        public ActionResult Supervisor()
        {
            var userId = User.Identity.GetUserId();
            var disputes = _context.Disputes
                .Include(d => d.Audit.Auditee)
                .Include(d => d.Audit.AuditTemplate)
                .Include(d => d.Audit.Auditor)
                .Include(d => d.Audit.Supervisor)
                .Where(d => d.Audit.SupervisorId == userId)
                .ToList();

            return View("Index", disputes);
        }

        public ActionResult SupervisorApprove(Guid id)
        {
            var submitDateTime = DateTime.Now;
            var userId = User.Identity.GetUserId();
            var user = _context.Users.Single(u => u.Id == userId);
            var dispute = _context.Disputes.Single(d => d.AuditId == id);

            dispute.SupervisorApproveDateTime = DateTime.Now;
            dispute.Comments = $"{user.NameFLUser} {submitDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")}\r\nSupervisor Approved Dispute" +
                "\r\n\r\n" + dispute.Comments;
            _context.SaveChanges();

            return RedirectToAction("Supervisor", dispute.AuditId);
        }

        public ActionResult SupervisorDeny(Guid id)
        {
            var submitDateTime = DateTime.Now;
            var userId = User.Identity.GetUserId();
            var user = _context.Users.Single(u => u.Id == userId);
            var dispute = _context.Disputes.Single(d => d.AuditId == id);

            dispute.DeciderId = User.Identity.GetUserId();
            dispute.DecisionId = _context.DisputeDecisions.Single(d => d.Text == "Invalid").Id;
            dispute.DecisionDateTime = DateTime.Now;
            dispute.Comments = $"{user.NameFLUser} {submitDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")}\r\nSupervisor Denied Dispute" +
                "\r\n\r\n" + dispute.Comments;
            _context.SaveChanges();

            return RedirectToAction("Supervisor", dispute.AuditId);
        }

        public ActionResult TeamDisputes()
        {
            var userId = User.Identity.GetUserId();
            var disputes = _context.Disputes
                .Include(d => d.Audit.Auditee)
                .Include(d => d.Audit.Auditor)
                .Include(d => d.Audit.AuditTemplate)
                .Include(d => d.Audit.Supervisor)
                .Include(d => d.Decision)
                .Where(d => d.Audit.SupervisorId == userId)
                .ToList();

            return View("Index", disputes);
        }
    }
}

DubbelVy/Views/Disputes/Create.cshtml
@model Dispute
@{
    ViewBag.Title = "Submit a Dispute";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Submit a Dispute</h2>
<hr />
<div id="audit" class="row">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(m => m.Audit.AuditeeId)</dt>
            <dd>@Model.Audit.Auditee.NameFLUser</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.SupervisorId)</dt>
            <dd>@Model.Audit.Supervisor.NameFLUser</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.WorkDateTime)</dt>
            <dd>@Model.Audit.WorkDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.WorkIdentifier)</dt>
            <dd>@Model.Audit.WorkIdentifier</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.Score)</dt>
            <dd>@Model.Audit.ScoreDisplay</dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>Audit Template</dt>
            <dd>@Model.Audit.AuditTemplate.TitleVersion</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.AuditDateTime)</dt>
            <dd>@Model.Audit.AuditDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.ModifiedDateTime)</dt>
            <dd>@Model.Audit.ModifiedDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
        </dl>
    </div>
</div>
<hr />

@using (Html.BeginForm("Create", "Disputes", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })
    @Html.HiddenFor(m => m.AuditId)

    <div class="form-group">
        @Html.LabelFor(m => m.Comments, new { @class = "col-md-2 control-label", @value = "What are you disputing?" })
        <p>Please provide a full desciption of why you are disputing this audit.  Being sure to note any related materials/trainings that support your claim.</p>
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Comments, new { @class = "form-control", @rows = "10" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    </div>
}


DubbelVy/Views/Disputes/Details.cshtml
@model DisputeViewModel
@{
    /**/

    ViewBag.Title = "Dispute Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dispute</h2>
<div id="audit" class="row">
    <div class="col-md-5">
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(m => m.Audit.AuditeeId)</dt>
            <dd>@Model.Audit.Auditee.NameFLUser</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.SupervisorId)</dt>
            <dd>@Model.Audit.Supervisor.NameFLUser</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.WorkDateTime)</dt>
            <dd>@Model.Audit.WorkDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.WorkIdentifier)</dt>
            <dd>@Model.Audit.WorkIdentifier</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.Score)</dt>
            <dd>@Model.Audit.ScoreDisplay</dd>
        </dl>
    </div>
    <div class="col-md-5">
        <dl class="dl-horizontal">
            <dt>Audit Template</dt>
            <dd>@Model.Audit.AuditTemplate.TitleVersion</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.AuditDateTime)</dt>
            <dd>@Model.Audit.AuditDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.ModifiedDateTime)</dt>
            <dd>@Model.Audit.ModifiedDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt></dt>
            <dd>@Html.ActionLink("Click here to view audit", "Details", "Audits", new { id = Model.AuditId }, new { @target = "_blank" })</dd>
        </dl>
    </div>
    <div class="col-md-2">
        @if (User.IsInRole("Admin") || User.IsInRole("Audit Manager") || User.Identity.GetUserId() == Model.Audit.SupervisorId)
        {
            <ul>
                <li>@Html.ActionLink("Supervisor Approve", "SupervisorApprove", new { id = Model.AuditId })</li>
                <li>@Html.ActionLink("Supervisor Deny", "SupervisorDeny", new { id = Model.AuditId })</li>
            </ul>
        }
    </div>
</div>
<div class="row" id="dispute">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(m => m.DeciderId)</dt>
            @if (Model.Decider != null)
            {
                <dd>@Model.Decider.NameFLUser</dd>
            }
            else
            {
                <dd></dd>
            }
            <dt>@Html.DisplayNameFor(m => m.DecisionId)</dt>
            @if (Model.Decision != null)
            {
                <dd>@Model.Decision.Text</dd>
            }
            else
            {
                <dd style="font-style:italic">Pending</dd>
            }
            <dt>@Html.DisplayNameFor(m => m.DecisionDateTime)</dt>
            @if (Model.DecisionDateTime.HasValue)
            {
                <dd>@Model.DecisionDateTime.Value.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            }
            else
            {
                <dd style="font-style:italic"></dd>
            }
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(m => m.CreateDateTime)</dt>
            <dd>@Model.CreateDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.SupervisorApproveDateTime)</dt>
            @if (Model.SupervisorApproveDateTime.HasValue)
            {
                <dd>@Model.SupervisorApproveDateTime.Value.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            }
            else
            {
                <dd></dd>
            }

        </dl>
    </div>
</div>
<h4>Comments</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Details", "Disputes", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })
            @Html.HiddenFor(m => m.AuditId)

            if ((User.IsInRole("Admin") || User.IsInRole("Audit Manager")) && User.Identity.GetUserId() != Model.Audit.AuditeeId)
            {
                <div class="form-group">
                    @Html.LabelFor(m => m.DecisionId, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.DecisionId, new SelectList(Model.DecisionOptions, "Id", "Text"), "", new { @class = "form-control" })
                    </div>
                </div>
            }

            <div class="form-group">
                @Html.LabelFor(m => m.NewComment, new { @class = "col-md-2 control-label", @value = "New Comment" })
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.NewComment, new { @class = "form-control", @rows = "10" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-default" value="Save" />
                </div>
            </div>
        }
    </div>
    <div class="col-md-6">
        <p style="white-space:pre-line">@Model.Comments</p>
    </div>
</div>

DubbelVy/Views/Disputes/Index.cshtml
@model IEnumerable<Dispute>
@{
    ViewBag.Title = "Audit Disputes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>
<hr />
<table class="table table-bordered table-hover table-responsive" id="disputes">
    <thead>
        <tr>
            <th>Dispute Date</th>
            <th>Auditee</th>
            <th>Work Date</th>
            <th>Work Identifier</th>
            <th>Auditor</th>
            <th>Audit Date</th>
            <th>Decision</th>
            <th>Decision Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var dispute in Model)
        {
            <tr>
                <td>@Html.ActionLink(dispute.CreateDateTime.ToString("MM/dd/yyyy"), "Details", new { id = dispute.AuditId }, null)</td>
                <td>@dispute.Audit.Auditee.NameFLUser</td>
                <td>@dispute.Audit.WorkDateTime.ToString("MM/dd/yyyy")</td>
                <td>@dispute.Audit.WorkIdentifier</td>
                <td>@dispute.Audit.Auditor.NameFLUser</td>
                <td>@dispute.Audit.AuditDateTime.ToString("MM/dd/yyyy")</td>
                @if(dispute.Decision == null)
                {
                    if(dispute.SupervisorApproveDateTime == null)
                    {
                        <td>Pending Supervisor Approval</td>
                    }
                    else
                    {
                        <td>Pending Decision</td>
                    }
                    <td>-</td>
                }
                else
                {
                    <td>@dispute.Decision.Text</td>
                    <td>@dispute.DecisionDateTime</td>
                }
            </tr>
        }
    </tbody>
</table>

@section scripts{
    <script>
        $(document).ready(function () {
            $("#disputes").DataTable();
        });
    </script>
    }

DubbelVy/Views/Disputes/Supervisor.cshtml
@model DisputeViewModel
@{
    ViewBag.Title = "Submit a Dispute";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dispute</h2>
<div id="audit" class="row">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(m => m.Audit.AuditeeId)</dt>
            <dd>@Model.Audit.Auditee.NameFLUser</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.SupervisorId)</dt>
            <dd>@Model.Audit.Supervisor.NameFLUser</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.WorkDateTime)</dt>
            <dd>@Model.Audit.WorkDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.WorkIdentifier)</dt>
            <dd>@Model.Audit.WorkIdentifier</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.Score)</dt>
            <dd>@Model.Audit.ScoreDisplay</dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>Audit Template</dt>
            <dd>@Model.Audit.AuditTemplate.TitleVersion</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.AuditDateTime)</dt>
            <dd>@Model.Audit.AuditDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.ModifiedDateTime)</dt>
            <dd>@Model.Audit.ModifiedDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt></dt>
            <dd>@Html.ActionLink("Click here to view audit", "Details", "Audits", new { id = Model.AuditId }, new { @target = "_blank" })</dd>
        </dl>
    </div>
</div>
<div class="row" id="dispute">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(m => m.DeciderId)</dt>
            @if (Model.Decider != null)
            {
                <dd>@Model.Decider.NameFLUser</dd>
            }
            else
            {
                <dd>-</dd>
            }
            <dt>@Html.DisplayNameFor(m => m.DecisionId)</dt>
            @if (Model.Decision != null)
            {
                <dd>@Model.Decision.Text</dd>
            }
            else
            {
                <dd style="font-style:italic">Pending</dd>
            }
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(m => m.CreateDateTime)</dt>
            <dd>@Model.CreateDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.SupervisorApproveDateTime)</dt>
            @if (Model.SupervisorApproveDateTime.HasValue)
            {
                <dd>@Model.SupervisorApproveDateTime.Value.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            }
            else
            {
                <dd>
                    @Html.ActionLink("Approve", "SupervisorApprove", new { id = Model.AuditId }) | 
                    @Html.ActionLink("Deny", "SupervisorDeny", new { id = Model.AuditId })
                </dd>
            }
            <dt>@Html.DisplayNameFor(m => m.DecisionDateTime)</dt>
            @if (Model.DecisionDateTime.HasValue)
            {
                <dd>@Model.DecisionDateTime.Value.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            }
            else
            {
                <dd style="font-style:italic">Pending</dd>
            }
        </dl>
    </div>
</div>
<hr />
<h4>Dispute Comments</h4>
<div id="comments">
    @using (Html.BeginForm("Supervisor", "Disputes", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.AuditId)

        <div class="form-group">
            @Html.LabelFor(m => m.NewComment, new { @class = "col-md-2 control-label", @value = "New Comment" })
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.NewComment, new { @class = "form-control", @rows = "10" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Submit" />
            </div>
        </div>
    }
        <p>
            @using (Html.BeginForm("Supervisor", "Disputes", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary("", new { @class = "text-danger" })
                @Html.HiddenFor(m => m.AuditId)
                @Html.HiddenFor(m => m.SupervisorApproveDateTime)
                @Html.HiddenFor(m => m.DeciderId)
                @Html.HiddenFor(m => m.DecisionId)
                @Html.HiddenFor(m => m.DecisionDateTime)

                <div class="form-group">
                    @Html.LabelFor(m => m.Comments, new { @class = "col-md-2 control-label", @value = "New Comment" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(m => m.Comments, new { @class = "form-control", @rows = "10" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-default" value="Submit" />
                    </div>
                </div>
            }
        </p>
</div>