DubbelVy/Controllers/AuditResponsesController.cs
using AutoMapper;
using Dubbelvy.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dubbelvy.Controllers
{
    public class AuditResponsesController : Controller
    {
        private ApplicationDbContext _context;

        public AuditResponsesController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult Edit(int id)
        {
            var auditResponse = _context.AuditResponses
                .Include(a => a.Audit.Auditee)
                .Include(a => a.Audit.AuditTemplate)
                .Include(a => a.Audit.Auditor)
                .Include(a => a.Audit.Supervisor)
                .Include(a => a.Element.Choices)
                .Single(a => a.Id == id);

            return View("Form", auditResponse);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AuditResponse model)
        {
            var userId = User.Identity.GetUserId();
            var submitDateTime = DateTime.Now;

            if(model.ChoiceId != null)
            {
                var auditResponse = _context.AuditResponses.Single(a => a.Id == model.Id);
                var audit = _context.Audits.Single(a => a.Id == model.AuditId);

                auditResponse.ChoiceId = model.ChoiceId;

                audit.ModifiedById = userId;
                audit.ModifiedDateTime = submitDateTime;
                audit.Score = null;

                _context.SaveChanges();

                return RedirectToAction("Details", "Audits", new { id = audit.Id });
            }

            model = _context.AuditResponses
                .Include(a => a.Audit.Auditee)
                .Include(a => a.Audit.AuditTemplate)
                .Include(a => a.Audit.Supervisor)
                .Include(a => a.Choice.Element.Section)
                .Single(a => a.Id == model.Id);

            return View("Form", model);
        }
    }
}

DubbelVy/Views/AuditResponses/Form.cshtml
@model AuditResponse
@{
    ViewBag.Title = "Audit Response - " + Model.Element.Topic;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Audit Information</h2>
<div id="audit" class="row">
    <div class="col-md-5">
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(m => m.Audit.AuditeeId)</dt>
            <dd>@Model.Audit.Auditee.NameFLUser</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.SupervisorId)</dt>
            <dd>@Model.Audit.Supervisor.NameFLUser</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.WorkDateTime)</dt>
            <dd>@Model.Audit.WorkDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.WorkIdentifier)</dt>
            <dd>@Model.Audit.WorkIdentifier</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.Score)</dt>
            <dd>@Model.Audit.ScoreDisplay</dd>
        </dl>
    </div>
    <div class="col-md-5">
        <dl class="dl-horizontal">
            <dt>Audit Template</dt>
            <dd>@Model.Audit.AuditTemplate.Title V@(Model.Audit.AuditTemplate.Version)</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.AuditorId)</dt>
            <dd>@Model.Audit.Auditor.NameFLUser</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.AuditDateTime)</dt>
            <dd>@Model.Audit.AuditDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.ModifiedById)</dt>
            <dd>@Model.Audit.ModifiedBy.NameFLUser</dd>
            <dt>@Html.DisplayNameFor(m => m.Audit.ModifiedDateTime)</dt>
            <dd>@Model.Audit.ModifiedDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
        </dl>
    </div>
</div>
<hr />

@using (Html.BeginForm("Edit", "AuditResponses", FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="form-group">
        @Html.DropDownListFor(m => m.ChoiceId, new SelectList(Model.Element.Choices, "Id", "Text"), new { @class = "form-control col-md-3", @style = "display:inline" })
        <p class="col-md-9" style="display:inline"><b>@Model.Element.Topic: </b>@Model.Element.Text</p>
    </div>
    
    <div class="hidden">
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.AuditId)
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Save" />
        </div>
    </div>
}
