DubbelVy/Models/AuditSection.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Dubbelvy.Models
{
    public class AuditSection
    {
        public int Id { get; set; }

        [Required]
        public string Description { get; set; }


        public int AuditTemplateId { get; set; }
        public AuditTemplate AuditTemplate { get; set; }

        public double? Weight { get; set; }
        public string WeightDisplay
        {
            get { return Weight != null ? (Weight * 100).ToString() + "%" : "Auto Fail"; }
        }

        public DateTime CreateDateTime { get; set; }

        [Required]
        public string CreatedById { get; set; }
        public ApplicationUser CreatedBy { get; set; }

        public DateTime ModifiedDateTime { get; set; }

        [Required]
        public string ModifiedById { get; set; }
        public ApplicationUser ModifiedBy { get; set; }

        public int Order { get; set; }

        public ICollection<AuditElement> Elements { get; set; }

        public void UpdateFromViewModel (AuditSectionViewModel viewModel)
        {
            Description = viewModel.Description;
            Weight = viewModel.Weight;
            ModifiedById = viewModel.ModifiedById;
            ModifiedDateTime = viewModel.ModifiedDateTime != null ? viewModel.ModifiedDateTime.Value : DateTime.Now;
            Order = viewModel.Order;
        }

        public double? GetTotalPossiblePoints(ApplicationDbContext _context)
        {
            Elements = _context.AuditElements
                .Where(e => e.SectionId == Id)
                .ToList();

            if(Elements.Count > 0)
            {
                double result = 0;
                foreach (var element in Elements)
                {
                    var elementPoints = element.GetTotalPossiblePoints(_context);
                    if(elementPoints.HasValue) { result += elementPoints.Value; }
                }
                return result;
            }

            return null;
        }
    }
}

DubbelVy/Models/AuditSectionViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Dubbelvy.Models
{
    public class AuditSectionViewModel
    {
        public int? Id { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Audit Template")]
        public int AuditTemplateId { get; set; }
        public AuditTemplateViewModel AuditTemplate { get; set; }

        public double? Weight { get; set; }
        [Display(Name = "Weight")]
        public string WeightDisplay
        {
            get { return Weight != null ? (Weight * 100).ToString() + "%" : "Auto Fail"; }
        }

        [Display(Name = "Created")]
        public DateTime? CreateDateTime { get; set; }

        [Display(Name = "Created by")]
        public string CreatedById { get; set; }
        public ApplicationUser CreatedBy { get; set; }

        [Display(Name = "Modified")]
        public DateTime? ModifiedDateTime { get; set; }

        [Display(Name = "Modified by")]
        public string ModifiedById { get; set; }
        public ApplicationUser ModifiedBy { get; set; }

        [Display(Name = "Display Order")]
        public int Order { get; set; }

        public List<AuditElementViewModel> Elements { get; set; }
    }
}

DubbelVy/Controllers/AuditSectionsController.cs
using AutoMapper;
using Dubbelvy.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dubbelvy.Controllers
{
    public class AuditSectionsController : Controller
    {
        private ApplicationDbContext _context;

        public AuditSectionsController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult Add(int id)
        {
            var auditTemplateId = id;
            var auditTemplate = _context.AuditTemplates.Single(a => a.Id == auditTemplateId);

            if(auditTemplate.GetCompletedAuditCount(_context) == 0)
            {
                var viewModel = new AuditSectionViewModel
                {
                    AuditTemplate = new AuditTemplateViewModel(),
                    AuditTemplateId = auditTemplateId
                };

                AutoMapper.Mapper.Map(auditTemplate, viewModel.AuditTemplate);

                return View("Form", viewModel);
            }

            ViewBag.Message = "Unable to add section to aduit template.  Audits have already been completed using this audit template.";
            return RedirectToAction("Details", "AuditTemplates", new { id = auditTemplateId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(AuditSectionViewModel model)
        {
            var userId = User.Identity.GetUserId();
            var submitDateTime = DateTime.Now;
            model.CreateDateTime = submitDateTime;
            model.ModifiedDateTime = submitDateTime;
            model.CreatedById = userId;
            model.ModifiedById = userId;

            var auditTemplate = _context.AuditTemplates.Single(a => a.Id == model.AuditTemplateId);

            if (ModelState.IsValid)
            {
                var newAuditSection = new AuditSection();

                AutoMapper.Mapper.Map(model, newAuditSection);
                auditTemplate.ModifiedById = userId;
                auditTemplate.ModifiedDateTime = submitDateTime;

                _context.AuditSections.Add(newAuditSection);
                _context.SaveChanges();

                return RedirectToAction("Details", "AuditTemplates", new { id = newAuditSection.AuditTemplateId });
            }

            model.AuditTemplate = new AuditTemplateViewModel();
            AutoMapper.Mapper.Map(auditTemplate, model.AuditTemplate);
            return View("Form", model);
        }

        public ActionResult Delete(int id)
        {
            var userId = User.Identity.GetUserId();
            var submitDateTime = DateTime.Now;
            var auditSection = _context.AuditSections.Single(a => a.Id == id);
            var auditTemplate = _context.AuditTemplates.Single(a => a.Id == auditSection.AuditTemplateId);

            if(auditTemplate.GetCompletedAuditCount(_context) == 0)
            {
                _context.AuditSections.Remove(auditSection);
                auditTemplate.ModifiedById = userId;
                auditTemplate.ModifiedDateTime = submitDateTime;

                _context.SaveChanges();

                ViewBag.Message = "Audit section deleted successfully.";

            }
            else
            {
                ViewBag.Message = "Unable to delete audit section.  Audits have been completed using the audit template that the section belongs to.";
            }

            return RedirectToAction("Details", "AuditTemplates", new { id = auditTemplate.Id });
        }

        public ActionResult Details(int id)
        {
            var auditSection = _context.AuditSections
                .Include(a => a.AuditTemplate)
                .Include(a => a.CreatedBy)
                .Include(a => a.ModifiedBy)
                .Single(a => a.Id == id);

            var viewModel = new AuditSectionViewModel();

            AutoMapper.Mapper.Map(auditSection, viewModel);

            return View(viewModel);
        }

        public ActionResult Edit(int id)
        {
            var auditSection = _context.AuditSections
                .Include(a => a.AuditTemplate)
                .Single(a => a.Id == id);

            if(auditSection.AuditTemplate.GetCompletedAuditCount(_context) == 0)
            {
                var viewModel = new AuditSectionViewModel();

                AutoMapper.Mapper.Map(auditSection, viewModel);

                return View("Form", viewModel);
            }

            ViewBag.Message = "Unable to edit audit section. Audits have been completed using the audit template that the section belongs to.";
            return RedirectToAction("Details", "AuditTemplates", new { id = auditSection.AuditTemplateId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AuditSectionViewModel model)
        {
            var auditSection = _context.AuditSections.Single(a => a.Id == model.Id);

            var userId = User.Identity.GetUserId();
            var submitDateTime = DateTime.Now;
            model.CreateDateTime = auditSection.CreateDateTime;
            model.ModifiedDateTime = submitDateTime;
            model.CreatedById = auditSection.CreatedById;
            model.ModifiedById = userId;

            var auditTemplate = _context.AuditTemplates.Single(a => a.Id == model.AuditTemplateId);

            if (ModelState.IsValid)
            {
                auditSection.UpdateFromViewModel(model);

                auditTemplate.ModifiedById = userId;
                auditTemplate.ModifiedDateTime = submitDateTime;
                _context.SaveChanges();

                return RedirectToAction("Details", "AuditTemplates", new { id = auditSection.AuditTemplateId });
            }

            model.AuditTemplate = new AuditTemplateViewModel();
            AutoMapper.Mapper.Map(auditTemplate, model.AuditTemplate);
            return View("Form", model);
        }
    }
}

DubbelVy/Views/AuditSections/Details.cshtml
@model AuditSectionViewModel
@{
    ViewBag.Title = "Audit Section Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>
<hr />
<div class="row">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(m => m.Description)</dt>
            <dd>@Model.Description</dd>
            <dt>@Html.DisplayNameFor(m => m.Weight)</dt>
            <dd>@Model.WeightDisplay</dd>
            <dt>@Html.DisplayNameFor(m => m.AuditTemplateId)</dt>
            <dd>
                @Html.ActionLink($"{Model.AuditTemplate.Title} V{Model.AuditTemplate.Version}", "Details", "AuditTemplates", new { id = Model.AuditTemplateId }, null)
            </dd>
        </dl>
    </div>
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(m => m.CreateDateTime)</dt>
            <dd>@Model.CreateDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.CreatedById)</dt>
            <dd>@Model.CreatedBy.NameFLUser</dd>
            <dt>@Html.DisplayNameFor(m => m.ModifiedDateTime)</dt>
            <dd>@Model.ModifiedDateTime.ToString("MM/dd/yyyy hh:mm:ss tt")</dd>
            <dt>@Html.DisplayNameFor(m => m.ModifiedById)</dt>
            <dd>@Model.ModifiedBy.NameFLUser</dd>
        </dl>
    </div>
</div>


DubbelVy/Views/AuditSections/Form.cshtml
@model AuditSectionViewModel
@{
    /**/

    ViewBag.Title = Model.Id != null ? "Edit Audit Section" : "New Audit Section";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>
<p style="font-style: italic">For @Model.AuditTemplate.Title V@(Model.AuditTemplate.Version)</p>
<hr />
@using (Html.BeginForm(Model.Id != null ? "Edit" : "Add", "AuditSections", FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Weight, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Weight, new { @class = "form-control" })
            <p style="font-style:italic">Enter as a decimal. Example, for 25% enter '0.25'. For Auto-Fail, leave blank.</p>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Order, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Order, new { @class = "form-control", @style = "display: inline" })
        </div>
    </div>
    <div class="hidden">
        @Html.HiddenFor(m => m.AuditTemplateId)
        @Html.HiddenFor(m => m.Id)
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value=@(Model.Id != null ? "Save" : "Create") />
        </div>
    </div>
}
